modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="grpgwaystones"
version="${file.jarVersion}"
displayName="GunsRPG Waystones"
authors="Toma,Tomano123"
updateJSONURL="https://raw.githubusercontent.com/Toma1O6/Guns-RPG-Waystones/master/update.json"
description='''
Addon mod for GUNSRPG. Adds new way of travelling via waystones
'''

[[dependencies.grpgwaystones]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.grpgwaystones]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.grpgwaystones]]
    modId="configuration"
    mandatory=true
    versionRange="[2.0,3.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.grpgwaystones]]
    modId="gunsrpg"
    mandatory=true
    versionRange="[1.5.0,2.0)"
    ordering="NONE"
    side="BOTH"